index:
    path: /
    controller: App\Controller\DefaultController::index

create_pack:
    path: /createPack
    controller: App\Controller\DefaultController::createPack
    methods: POST

# Auth
app_register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

app_login:
    path: /login
    methods: POST

app_logout:
    path: /logout
# End Auth